// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bolao.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBolao = `-- name: CreateBolao :one
INSERT INTO boloes (name, admin_id)
VALUES ($1, $2)
RETURNING id, name, admin_id, invite_token, created_at, updated_at, retroativo_enabled, taxa_entrada, wa_group_jid
`

type CreateBolaoParams struct {
	Name    string      `json:"name"`
	AdminID pgtype.UUID `json:"admin_id"`
}

func (q *Queries) CreateBolao(ctx context.Context, arg CreateBolaoParams) (Bolo, error) {
	row := q.db.QueryRow(ctx, createBolao, arg.Name, arg.AdminID)
	var i Bolo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetroativoEnabled,
		&i.TaxaEntrada,
		&i.WaGroupJid,
	)
	return i, err
}

const deleteBolao = `-- name: DeleteBolao :exec
DELETE FROM boloes WHERE id = $1 AND admin_id = $2
`

type DeleteBolaoParams struct {
	ID      pgtype.UUID `json:"id"`
	AdminID pgtype.UUID `json:"admin_id"`
}

func (q *Queries) DeleteBolao(ctx context.Context, arg DeleteBolaoParams) error {
	_, err := q.db.Exec(ctx, deleteBolao, arg.ID, arg.AdminID)
	return err
}

const getBolaoByID = `-- name: GetBolaoByID :one
SELECT id, name, admin_id, invite_token, created_at, updated_at, retroativo_enabled, taxa_entrada, wa_group_jid FROM boloes WHERE id = $1
`

func (q *Queries) GetBolaoByID(ctx context.Context, id pgtype.UUID) (Bolo, error) {
	row := q.db.QueryRow(ctx, getBolaoByID, id)
	var i Bolo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetroativoEnabled,
		&i.TaxaEntrada,
		&i.WaGroupJid,
	)
	return i, err
}

const getBolaoByInviteToken = `-- name: GetBolaoByInviteToken :one
SELECT id, name, admin_id, invite_token, created_at, updated_at, retroativo_enabled, taxa_entrada, wa_group_jid FROM boloes WHERE invite_token = $1
`

func (q *Queries) GetBolaoByInviteToken(ctx context.Context, inviteToken string) (Bolo, error) {
	row := q.db.QueryRow(ctx, getBolaoByInviteToken, inviteToken)
	var i Bolo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetroativoEnabled,
		&i.TaxaEntrada,
		&i.WaGroupJid,
	)
	return i, err
}

const getBolaoWAGroup = `-- name: GetBolaoWAGroup :one
SELECT wa_group_jid FROM boloes WHERE id = $1
`

func (q *Queries) GetBolaoWAGroup(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBolaoWAGroup, id)
	var wa_group_jid pgtype.Text
	err := row.Scan(&wa_group_jid)
	return wa_group_jid, err
}

const listBoloesByJogo = `-- name: ListBoloesByJogo :many
SELECT DISTINCT b.id, b.name, b.admin_id, b.invite_token, b.created_at, b.updated_at, b.retroativo_enabled, b.taxa_entrada, b.wa_group_jid
FROM boloes b
JOIN palpites p ON p.bolao_id = b.id
WHERE p.jogo_id = $1
  AND b.wa_group_jid IS NOT NULL
  AND b.wa_group_jid != ''
ORDER BY b.created_at
`

func (q *Queries) ListBoloesByJogo(ctx context.Context, jogoID pgtype.UUID) ([]Bolo, error) {
	rows, err := q.db.Query(ctx, listBoloesByJogo, jogoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bolo
	for rows.Next() {
		var i Bolo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AdminID,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetroativoEnabled,
			&i.TaxaEntrada,
			&i.WaGroupJid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoloesByUser = `-- name: ListBoloesByUser :many
SELECT b.id, b.name, b.admin_id, b.invite_token, b.created_at, b.updated_at, b.retroativo_enabled, b.taxa_entrada, b.wa_group_jid FROM boloes b
JOIN participantes p ON p.bolao_id = b.id
WHERE p.user_id = $1
ORDER BY b.created_at DESC
`

func (q *Queries) ListBoloesByUser(ctx context.Context, userID pgtype.UUID) ([]Bolo, error) {
	rows, err := q.db.Query(ctx, listBoloesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bolo
	for rows.Next() {
		var i Bolo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AdminID,
			&i.InviteToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetroativoEnabled,
			&i.TaxaEntrada,
			&i.WaGroupJid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateInviteToken = `-- name: RegenerateInviteToken :one
UPDATE boloes
SET invite_token = encode(gen_random_bytes(32), 'hex'), updated_at = NOW()
WHERE id = $1 AND admin_id = $2
RETURNING id, name, admin_id, invite_token, created_at, updated_at, retroativo_enabled, taxa_entrada, wa_group_jid
`

type RegenerateInviteTokenParams struct {
	ID      pgtype.UUID `json:"id"`
	AdminID pgtype.UUID `json:"admin_id"`
}

func (q *Queries) RegenerateInviteToken(ctx context.Context, arg RegenerateInviteTokenParams) (Bolo, error) {
	row := q.db.QueryRow(ctx, regenerateInviteToken, arg.ID, arg.AdminID)
	var i Bolo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetroativoEnabled,
		&i.TaxaEntrada,
		&i.WaGroupJid,
	)
	return i, err
}

const setBolaoWAGroup = `-- name: SetBolaoWAGroup :one
UPDATE boloes SET wa_group_jid = $2, updated_at = NOW() WHERE id = $1 RETURNING id, name, admin_id, invite_token, created_at, updated_at, retroativo_enabled, taxa_entrada, wa_group_jid
`

type SetBolaoWAGroupParams struct {
	ID         pgtype.UUID `json:"id"`
	WaGroupJid pgtype.Text `json:"wa_group_jid"`
}

func (q *Queries) SetBolaoWAGroup(ctx context.Context, arg SetBolaoWAGroupParams) (Bolo, error) {
	row := q.db.QueryRow(ctx, setBolaoWAGroup, arg.ID, arg.WaGroupJid)
	var i Bolo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetroativoEnabled,
		&i.TaxaEntrada,
		&i.WaGroupJid,
	)
	return i, err
}

const setRetroativoEnabled = `-- name: SetRetroativoEnabled :one
UPDATE boloes
SET retroativo_enabled = $3, updated_at = NOW()
WHERE id = $1 AND admin_id = $2
RETURNING id, name, admin_id, invite_token, created_at, updated_at, retroativo_enabled, taxa_entrada, wa_group_jid
`

type SetRetroativoEnabledParams struct {
	ID                pgtype.UUID `json:"id"`
	AdminID           pgtype.UUID `json:"admin_id"`
	RetroativoEnabled bool        `json:"retroativo_enabled"`
}

func (q *Queries) SetRetroativoEnabled(ctx context.Context, arg SetRetroativoEnabledParams) (Bolo, error) {
	row := q.db.QueryRow(ctx, setRetroativoEnabled, arg.ID, arg.AdminID, arg.RetroativoEnabled)
	var i Bolo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetroativoEnabled,
		&i.TaxaEntrada,
		&i.WaGroupJid,
	)
	return i, err
}
