// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jogo.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJogoByID = `-- name: GetJogoByID :one
SELECT id, external_id, home_team, away_team, home_team_flag, away_team_flag, starts_at, stage, home_score, away_score, finished, created_at, updated_at FROM jogos WHERE id = $1
`

func (q *Queries) GetJogoByID(ctx context.Context, id pgtype.UUID) (Jogo, error) {
	row := q.db.QueryRow(ctx, getJogoByID, id)
	var i Jogo
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.HomeTeamFlag,
		&i.AwayTeamFlag,
		&i.StartsAt,
		&i.Stage,
		&i.HomeScore,
		&i.AwayScore,
		&i.Finished,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFinishedJobsWithoutScores = `-- name: ListFinishedJobsWithoutScores :many
SELECT id, external_id, home_team, away_team, home_team_flag, away_team_flag, starts_at, stage, home_score, away_score, finished, created_at, updated_at FROM jogos WHERE finished = TRUE AND home_score IS NOT NULL
`

func (q *Queries) ListFinishedJobsWithoutScores(ctx context.Context) ([]Jogo, error) {
	rows, err := q.db.Query(ctx, listFinishedJobsWithoutScores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jogo
	for rows.Next() {
		var i Jogo
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.HomeTeamFlag,
			&i.AwayTeamFlag,
			&i.StartsAt,
			&i.Stage,
			&i.HomeScore,
			&i.AwayScore,
			&i.Finished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJogos = `-- name: ListJogos :many
SELECT id, external_id, home_team, away_team, home_team_flag, away_team_flag, starts_at, stage, home_score, away_score, finished, created_at, updated_at FROM jogos ORDER BY starts_at ASC
`

func (q *Queries) ListJogos(ctx context.Context) ([]Jogo, error) {
	rows, err := q.db.Query(ctx, listJogos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jogo
	for rows.Next() {
		var i Jogo
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.HomeTeamFlag,
			&i.AwayTeamFlag,
			&i.StartsAt,
			&i.Stage,
			&i.HomeScore,
			&i.AwayScore,
			&i.Finished,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJogo = `-- name: UpsertJogo :one
WITH before AS (
    SELECT finished FROM jogos WHERE external_id = $1
)
INSERT INTO jogos (external_id, home_team, away_team, home_team_flag, away_team_flag, starts_at, stage, home_score, away_score, finished)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (external_id) DO UPDATE
    SET home_team      = EXCLUDED.home_team,
        away_team      = EXCLUDED.away_team,
        home_team_flag = EXCLUDED.home_team_flag,
        away_team_flag = EXCLUDED.away_team_flag,
        starts_at      = EXCLUDED.starts_at,
        stage          = EXCLUDED.stage,
        home_score     = EXCLUDED.home_score,
        away_score     = EXCLUDED.away_score,
        finished       = EXCLUDED.finished,
        updated_at     = NOW()
RETURNING id, external_id, home_team, away_team, home_team_flag, away_team_flag, starts_at, stage, home_score, away_score, finished, created_at, updated_at, (SELECT COALESCE(finished, FALSE) FROM before) AS was_finished
`

type UpsertJogoParams struct {
	ExternalID   string             `json:"external_id"`
	HomeTeam     string             `json:"home_team"`
	AwayTeam     string             `json:"away_team"`
	HomeTeamFlag pgtype.Text        `json:"home_team_flag"`
	AwayTeamFlag pgtype.Text        `json:"away_team_flag"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	Stage        string             `json:"stage"`
	HomeScore    pgtype.Int4        `json:"home_score"`
	AwayScore    pgtype.Int4        `json:"away_score"`
	Finished     bool               `json:"finished"`
}

type UpsertJogoRow struct {
	ID           pgtype.UUID        `json:"id"`
	ExternalID   string             `json:"external_id"`
	HomeTeam     string             `json:"home_team"`
	AwayTeam     string             `json:"away_team"`
	HomeTeamFlag pgtype.Text        `json:"home_team_flag"`
	AwayTeamFlag pgtype.Text        `json:"away_team_flag"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	Stage        string             `json:"stage"`
	HomeScore    pgtype.Int4        `json:"home_score"`
	AwayScore    pgtype.Int4        `json:"away_score"`
	Finished     bool               `json:"finished"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	WasFinished  bool               `json:"was_finished"`
}

func (q *Queries) UpsertJogo(ctx context.Context, arg UpsertJogoParams) (UpsertJogoRow, error) {
	row := q.db.QueryRow(ctx, upsertJogo,
		arg.ExternalID,
		arg.HomeTeam,
		arg.AwayTeam,
		arg.HomeTeamFlag,
		arg.AwayTeamFlag,
		arg.StartsAt,
		arg.Stage,
		arg.HomeScore,
		arg.AwayScore,
		arg.Finished,
	)
	var i UpsertJogoRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.HomeTeamFlag,
		&i.AwayTeamFlag,
		&i.StartsAt,
		&i.Stage,
		&i.HomeScore,
		&i.AwayScore,
		&i.Finished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WasFinished,
	)
	return i, err
}
