// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bolo struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	AdminID     pgtype.UUID        `json:"admin_id"`
	InviteToken string             `json:"invite_token"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Jogo struct {
	ID           pgtype.UUID        `json:"id"`
	ExternalID   string             `json:"external_id"`
	HomeTeam     string             `json:"home_team"`
	AwayTeam     string             `json:"away_team"`
	HomeTeamFlag pgtype.Text        `json:"home_team_flag"`
	AwayTeamFlag pgtype.Text        `json:"away_team_flag"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	Stage        string             `json:"stage"`
	HomeScore    pgtype.Int4        `json:"home_score"`
	AwayScore    pgtype.Int4        `json:"away_score"`
	Finished     bool               `json:"finished"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Palpite struct {
	ID        pgtype.UUID        `json:"id"`
	BolaoID   pgtype.UUID        `json:"bolao_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	JogoID    pgtype.UUID        `json:"jogo_id"`
	HomeScore int32              `json:"home_score"`
	AwayScore int32              `json:"away_score"`
	Pontos    pgtype.Int4        `json:"pontos"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Participante struct {
	ID       pgtype.UUID        `json:"id"`
	BolaoID  pgtype.UUID        `json:"bolao_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	GoogleID     pgtype.Text        `json:"google_id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
