// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FeedTipo string

const (
	FeedTipoPalpiteRegistrado  FeedTipo = "palpite_registrado"
	FeedTipoPalpiteAlterado    FeedTipo = "palpite_alterado"
	FeedTipoParticipanteEntrou FeedTipo = "participante_entrou"
	FeedTipoJogoIniciado       FeedTipo = "jogo_iniciado"
	FeedTipoResultadoApurado   FeedTipo = "resultado_apurado"
	FeedTipoPalpiteRemovido    FeedTipo = "palpite_removido"
	FeedTipoTaxaAprovada       FeedTipo = "taxa_aprovada"
)

func (e *FeedTipo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeedTipo(s)
	case string:
		*e = FeedTipo(s)
	default:
		return fmt.Errorf("unsupported scan type for FeedTipo: %T", src)
	}
	return nil
}

type NullFeedTipo struct {
	FeedTipo FeedTipo `json:"feed_tipo"`
	Valid    bool     `json:"valid"` // Valid is true if FeedTipo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeedTipo) Scan(value interface{}) error {
	if value == nil {
		ns.FeedTipo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeedTipo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeedTipo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeedTipo), nil
}

type Bolo struct {
	ID                     pgtype.UUID        `json:"id"`
	Name                   string             `json:"name"`
	AdminID                pgtype.UUID        `json:"admin_id"`
	InviteToken            string             `json:"invite_token"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	RetroativoEnabled      bool               `json:"retroativo_enabled"`
	TaxaEntrada            pgtype.Numeric     `json:"taxa_entrada"`
	WaGroupJid             pgtype.Text        `json:"wa_group_jid"`
	WaNotificationsEnabled bool               `json:"wa_notifications_enabled"`
}

type FeedEvento struct {
	ID        pgtype.UUID        `json:"id"`
	BolaoID   pgtype.UUID        `json:"bolao_id"`
	Tipo      FeedTipo           `json:"tipo"`
	UserID    pgtype.UUID        `json:"user_id"`
	JogoID    pgtype.UUID        `json:"jogo_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Jogo struct {
	ID           pgtype.UUID        `json:"id"`
	ExternalID   string             `json:"external_id"`
	HomeTeam     string             `json:"home_team"`
	AwayTeam     string             `json:"away_team"`
	HomeTeamFlag pgtype.Text        `json:"home_team_flag"`
	AwayTeamFlag pgtype.Text        `json:"away_team_flag"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	Stage        string             `json:"stage"`
	HomeScore    pgtype.Int4        `json:"home_score"`
	AwayScore    pgtype.Int4        `json:"away_score"`
	Finished     bool               `json:"finished"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Winner       pgtype.Text        `json:"winner"`
}

type JogoNotification struct {
	JogoID           pgtype.UUID        `json:"jogo_id"`
	NotificationType string             `json:"notification_type"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
}

type Palpite struct {
	ID            pgtype.UUID        `json:"id"`
	BolaoID       pgtype.UUID        `json:"bolao_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	JogoID        pgtype.UUID        `json:"jogo_id"`
	HomeScore     int32              `json:"home_score"`
	AwayScore     int32              `json:"away_score"`
	Pontos        pgtype.Numeric     `json:"pontos"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Status        string             `json:"status"`
	PenaltyWinner pgtype.Text        `json:"penalty_winner"`
}

type Participante struct {
	ID       pgtype.UUID        `json:"id"`
	BolaoID  pgtype.UUID        `json:"bolao_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type TaxaEntradaProposta struct {
	ID          pgtype.UUID        `json:"id"`
	BolaoID     pgtype.UUID        `json:"bolao_id"`
	Valor       pgtype.Numeric     `json:"valor"`
	PropostaPor pgtype.UUID        `json:"proposta_por"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TaxaEntradaVoto struct {
	ID         pgtype.UUID        `json:"id"`
	PropostaID pgtype.UUID        `json:"proposta_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Aprovado   bool               `json:"aprovado"`
	VotedAt    pgtype.Timestamptz `json:"voted_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	GoogleID     pgtype.Text        `json:"google_id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash pgtype.Text        `json:"password_hash"`
}
