// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: palpite.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRanking = `-- name: GetRanking :many
SELECT
    u.id AS user_id,
    u.name AS user_name,
    u.avatar_url,
    COALESCE(SUM(p.pontos), 0) AS total_pontos,
    COUNT(p.id) FILTER (WHERE p.pontos IS NOT NULL) AS palpites_computados
FROM participantes pt
JOIN users u ON u.id = pt.user_id
LEFT JOIN palpites p ON p.user_id = pt.user_id AND p.bolao_id = pt.bolao_id
WHERE pt.bolao_id = $1
GROUP BY u.id, u.name, u.avatar_url
ORDER BY total_pontos DESC, u.name ASC
`

type GetRankingRow struct {
	UserID             pgtype.UUID `json:"user_id"`
	UserName           string      `json:"user_name"`
	AvatarUrl          pgtype.Text `json:"avatar_url"`
	TotalPontos        interface{} `json:"total_pontos"`
	PalpitesComputados int64       `json:"palpites_computados"`
}

func (q *Queries) GetRanking(ctx context.Context, bolaoID pgtype.UUID) ([]GetRankingRow, error) {
	rows, err := q.db.Query(ctx, getRanking, bolaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRankingRow
	for rows.Next() {
		var i GetRankingRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.AvatarUrl,
			&i.TotalPontos,
			&i.PalpitesComputados,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPalpitesByBolaoAndJogo = `-- name: ListPalpitesByBolaoAndJogo :many
SELECT p.id, p.bolao_id, p.user_id, p.jogo_id, p.home_score, p.away_score, p.pontos, p.created_at, p.updated_at, u.name AS user_name, u.avatar_url AS user_avatar
FROM palpites p
JOIN users u ON u.id = p.user_id
WHERE p.bolao_id = $1 AND p.jogo_id = $2
`

type ListPalpitesByBolaoAndJogoParams struct {
	BolaoID pgtype.UUID `json:"bolao_id"`
	JogoID  pgtype.UUID `json:"jogo_id"`
}

type ListPalpitesByBolaoAndJogoRow struct {
	ID         pgtype.UUID        `json:"id"`
	BolaoID    pgtype.UUID        `json:"bolao_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	JogoID     pgtype.UUID        `json:"jogo_id"`
	HomeScore  int32              `json:"home_score"`
	AwayScore  int32              `json:"away_score"`
	Pontos     pgtype.Int4        `json:"pontos"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserName   string             `json:"user_name"`
	UserAvatar pgtype.Text        `json:"user_avatar"`
}

func (q *Queries) ListPalpitesByBolaoAndJogo(ctx context.Context, arg ListPalpitesByBolaoAndJogoParams) ([]ListPalpitesByBolaoAndJogoRow, error) {
	rows, err := q.db.Query(ctx, listPalpitesByBolaoAndJogo, arg.BolaoID, arg.JogoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPalpitesByBolaoAndJogoRow
	for rows.Next() {
		var i ListPalpitesByBolaoAndJogoRow
		if err := rows.Scan(
			&i.ID,
			&i.BolaoID,
			&i.UserID,
			&i.JogoID,
			&i.HomeScore,
			&i.AwayScore,
			&i.Pontos,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPalpitesByBolaoAndUser = `-- name: ListPalpitesByBolaoAndUser :many
SELECT id, bolao_id, user_id, jogo_id, home_score, away_score, pontos, created_at, updated_at FROM palpites WHERE bolao_id = $1 AND user_id = $2 ORDER BY created_at ASC
`

type ListPalpitesByBolaoAndUserParams struct {
	BolaoID pgtype.UUID `json:"bolao_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListPalpitesByBolaoAndUser(ctx context.Context, arg ListPalpitesByBolaoAndUserParams) ([]Palpite, error) {
	rows, err := q.db.Query(ctx, listPalpitesByBolaoAndUser, arg.BolaoID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Palpite
	for rows.Next() {
		var i Palpite
		if err := rows.Scan(
			&i.ID,
			&i.BolaoID,
			&i.UserID,
			&i.JogoID,
			&i.HomeScore,
			&i.AwayScore,
			&i.Pontos,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePalpitePontos = `-- name: UpdatePalpitePontos :exec
UPDATE palpites SET pontos = $1, updated_at = NOW()
WHERE bolao_id = $2 AND jogo_id = $3 AND user_id = $4
`

type UpdatePalpitePontosParams struct {
	Pontos  pgtype.Int4 `json:"pontos"`
	BolaoID pgtype.UUID `json:"bolao_id"`
	JogoID  pgtype.UUID `json:"jogo_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdatePalpitePontos(ctx context.Context, arg UpdatePalpitePontosParams) error {
	_, err := q.db.Exec(ctx, updatePalpitePontos,
		arg.Pontos,
		arg.BolaoID,
		arg.JogoID,
		arg.UserID,
	)
	return err
}

const upsertPalpite = `-- name: UpsertPalpite :one
INSERT INTO palpites (bolao_id, user_id, jogo_id, home_score, away_score)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (bolao_id, user_id, jogo_id) DO UPDATE
    SET home_score = EXCLUDED.home_score,
        away_score = EXCLUDED.away_score,
        updated_at = NOW()
RETURNING id, bolao_id, user_id, jogo_id, home_score, away_score, pontos, created_at, updated_at
`

type UpsertPalpiteParams struct {
	BolaoID   pgtype.UUID `json:"bolao_id"`
	UserID    pgtype.UUID `json:"user_id"`
	JogoID    pgtype.UUID `json:"jogo_id"`
	HomeScore int32       `json:"home_score"`
	AwayScore int32       `json:"away_score"`
}

func (q *Queries) UpsertPalpite(ctx context.Context, arg UpsertPalpiteParams) (Palpite, error) {
	row := q.db.QueryRow(ctx, upsertPalpite,
		arg.BolaoID,
		arg.UserID,
		arg.JogoID,
		arg.HomeScore,
		arg.AwayScore,
	)
	var i Palpite
	err := row.Scan(
		&i.ID,
		&i.BolaoID,
		&i.UserID,
		&i.JogoID,
		&i.HomeScore,
		&i.AwayScore,
		&i.Pontos,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPalpitesByJogo = `-- name: ListPalpitesByJogo :many
SELECT id, bolao_id, user_id, jogo_id, home_score, away_score, pontos, created_at, updated_at FROM palpites WHERE jogo_id = $1
`

func (q *Queries) ListPalpitesByJogo(ctx context.Context, jogoID pgtype.UUID) ([]Palpite, error) {
	rows, err := q.db.Query(ctx, listPalpitesByJogo, jogoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Palpite
	for rows.Next() {
		var i Palpite
		if err := rows.Scan(
			&i.ID,
			&i.BolaoID,
			&i.UserID,
			&i.JogoID,
			&i.HomeScore,
			&i.AwayScore,
			&i.Pontos,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
