// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participante.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isParticipante = `-- name: IsParticipante :one
SELECT EXISTS(
    SELECT 1 FROM participantes WHERE bolao_id = $1 AND user_id = $2
) AS is_participante
`

type IsParticipanteParams struct {
	BolaoID pgtype.UUID `json:"bolao_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsParticipante(ctx context.Context, arg IsParticipanteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipante, arg.BolaoID, arg.UserID)
	var is_participante bool
	err := row.Scan(&is_participante)
	return is_participante, err
}

const joinBolao = `-- name: JoinBolao :one
INSERT INTO participantes (bolao_id, user_id)
VALUES ($1, $2)
ON CONFLICT (bolao_id, user_id) DO UPDATE SET joined_at = participantes.joined_at
RETURNING id, bolao_id, user_id, joined_at
`

type JoinBolaoParams struct {
	BolaoID pgtype.UUID `json:"bolao_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) JoinBolao(ctx context.Context, arg JoinBolaoParams) (Participante, error) {
	row := q.db.QueryRow(ctx, joinBolao, arg.BolaoID, arg.UserID)
	var i Participante
	err := row.Scan(
		&i.ID,
		&i.BolaoID,
		&i.UserID,
		&i.JoinedAt,
	)
	return i, err
}

const listParticipantesByBolao = `-- name: ListParticipantesByBolao :many
SELECT p.id, p.bolao_id, p.user_id, p.joined_at, u.name AS user_name, u.avatar_url AS user_avatar
FROM participantes p
JOIN users u ON u.id = p.user_id
WHERE p.bolao_id = $1
ORDER BY p.joined_at ASC
`

type ListParticipantesByBolaoRow struct {
	ID         pgtype.UUID        `json:"id"`
	BolaoID    pgtype.UUID        `json:"bolao_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
	UserName   string             `json:"user_name"`
	UserAvatar pgtype.Text        `json:"user_avatar"`
}

func (q *Queries) ListParticipantesByBolao(ctx context.Context, bolaoID pgtype.UUID) ([]ListParticipantesByBolaoRow, error) {
	rows, err := q.db.Query(ctx, listParticipantesByBolao, bolaoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantesByBolaoRow
	for rows.Next() {
		var i ListParticipantesByBolaoRow
		if err := rows.Scan(
			&i.ID,
			&i.BolaoID,
			&i.UserID,
			&i.JoinedAt,
			&i.UserName,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantesSemPalpite = `-- name: ListParticipantesSemPalpite :many
SELECT u.id AS user_id, u.name AS user_name
FROM participantes pt
JOIN users u ON u.id = pt.user_id
WHERE pt.bolao_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM palpites p
    WHERE p.bolao_id = pt.bolao_id AND p.jogo_id = $2 AND p.user_id = pt.user_id
  )
ORDER BY u.name ASC
`

type ListParticipantesSemPalpiteParams struct {
	BolaoID pgtype.UUID `json:"bolao_id"`
	JogoID  pgtype.UUID `json:"jogo_id"`
}

type ListParticipantesSemPalpiteRow struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserName string      `json:"user_name"`
}

func (q *Queries) ListParticipantesSemPalpite(ctx context.Context, arg ListParticipantesSemPalpiteParams) ([]ListParticipantesSemPalpiteRow, error) {
	rows, err := q.db.Query(ctx, listParticipantesSemPalpite, arg.BolaoID, arg.JogoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantesSemPalpiteRow
	for rows.Next() {
		var i ListParticipantesSemPalpiteRow
		if err := rows.Scan(&i.UserID, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
