// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AtualizarStatusPalpite(ctx context.Context, arg AtualizarStatusPalpiteParams) (Palpite, error)
	CancelarProposta(ctx context.Context, bolaoID pgtype.UUID) error
	CountParticipantesNaMomento(ctx context.Context, arg CountParticipantesNaMomentoParams) (int64, error)
	// Counts favorable votes only from participants eligible at proposal time (joined_at <= proposta.created_at).
	// This ensures the same population is used for both total and favorable counts.
	CountVotosFavoraveis(ctx context.Context, arg CountVotosFavoraveisParams) (int64, error)
	CreateBolao(ctx context.Context, arg CreateBolaoParams) (Bolo, error)
	CreateUserByEmail(ctx context.Context, arg CreateUserByEmailParams) (User, error)
	DefinirTaxa(ctx context.Context, arg DefinirTaxaParams) (Bolo, error)
	DeleteBolao(ctx context.Context, arg DeleteBolaoParams) error
	DeletePalpite(ctx context.Context, arg DeletePalpiteParams) error
	GetBolaoByID(ctx context.Context, id pgtype.UUID) (Bolo, error)
	GetBolaoByInviteToken(ctx context.Context, inviteToken string) (Bolo, error)
	GetBolaoWAGroup(ctx context.Context, id pgtype.UUID) (pgtype.Text, error)
	GetJogoByID(ctx context.Context, id pgtype.UUID) (Jogo, error)
	GetMeuVoto(ctx context.Context, arg GetMeuVotoParams) (bool, error)
	GetPalpiteByID(ctx context.Context, arg GetPalpiteByIDParams) (Palpite, error)
	GetPropostaAtiva(ctx context.Context, bolaoID pgtype.UUID) (TaxaEntradaProposta, error)
	GetPropostaAtivaForUpdate(ctx context.Context, bolaoID pgtype.UUID) (TaxaEntradaProposta, error)
	GetRanking(ctx context.Context, bolaoID pgtype.UUID) ([]GetRankingRow, error)
	GetTaxaEntrada(ctx context.Context, id pgtype.UUID) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertFeedEvento(ctx context.Context, arg InsertFeedEventoParams) (FeedEvento, error)
	IsParticipante(ctx context.Context, arg IsParticipanteParams) (bool, error)
	// Returns true if the user was a participant at or before proposta.created_at.
	IsParticipanteElegivel(ctx context.Context, arg IsParticipanteElegivelParams) (bool, error)
	JoinBolao(ctx context.Context, arg JoinBolaoParams) (Participante, error)
	ListBoloesByJogo(ctx context.Context, jogoID pgtype.UUID) ([]Bolo, error)
	ListBoloesByUser(ctx context.Context, userID pgtype.UUID) ([]Bolo, error)
	ListBoloesByWAGroup(ctx context.Context) ([]Bolo, error)
	ListFeedByBolao(ctx context.Context, bolaoID pgtype.UUID) ([]ListFeedByBolaoRow, error)
	ListFinishedJobsWithoutScores(ctx context.Context) ([]Jogo, error)
	ListJogos(ctx context.Context) ([]Jogo, error)
	ListPalpitesByBolaoAndJogo(ctx context.Context, arg ListPalpitesByBolaoAndJogoParams) ([]ListPalpitesByBolaoAndJogoRow, error)
	ListPalpitesByBolaoAndUser(ctx context.Context, arg ListPalpitesByBolaoAndUserParams) ([]Palpite, error)
	ListPalpitesByJogo(ctx context.Context, jogoID pgtype.UUID) ([]Palpite, error)
	ListPalpitesPendentes(ctx context.Context, bolaoID pgtype.UUID) ([]ListPalpitesPendentesRow, error)
	ListPalpitesRetroativosAprovados(ctx context.Context, bolaoID pgtype.UUID) ([]ListPalpitesRetroativosAprovadosRow, error)
	ListParticipantesByBolao(ctx context.Context, bolaoID pgtype.UUID) ([]ListParticipantesByBolaoRow, error)
	ProporTaxa(ctx context.Context, arg ProporTaxaParams) (TaxaEntradaProposta, error)
	RegenerateInviteToken(ctx context.Context, arg RegenerateInviteTokenParams) (Bolo, error)
	// ON CONFLICT DO NOTHING: when user already voted, RETURNING yields no rows.
	// pgx returns pgx.ErrNoRows, which the service maps to ErrJaVotou.
	// Do NOT change to DO UPDATE without updating the service layer.
	RegistrarVoto(ctx context.Context, arg RegistrarVotoParams) (TaxaEntradaVoto, error)
	SetBolaoWAGroup(ctx context.Context, arg SetBolaoWAGroupParams) (Bolo, error)
	SetBolaoWANotificationsEnabled(ctx context.Context, arg SetBolaoWANotificationsEnabledParams) (Bolo, error)
	SetRetroativoEnabled(ctx context.Context, arg SetRetroativoEnabledParams) (Bolo, error)
	UpdatePalpitePontos(ctx context.Context, arg UpdatePalpitePontosParams) error
	UpsertJogo(ctx context.Context, arg UpsertJogoParams) (UpsertJogoRow, error)
	UpsertPalpite(ctx context.Context, arg UpsertPalpiteParams) (Palpite, error)
	// When the conflict row has status='aprovado', the WHERE clause causes Postgres to skip
	// the DO UPDATE, and RETURNING emits 0 rows. pgx surfaces this as pgx.ErrNoRows,
	// which the service maps to ErrPalpiteJaAprovado.
	UpsertPalpiteRetroativo(ctx context.Context, arg UpsertPalpiteRetroativoParams) (Palpite, error)
	UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
