// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBolao(ctx context.Context, arg CreateBolaoParams) (Bolo, error)
	CreateUserByEmail(ctx context.Context, arg CreateUserByEmailParams) (User, error)
	GetBolaoByID(ctx context.Context, id pgtype.UUID) (Bolo, error)
	GetBolaoByInviteToken(ctx context.Context, inviteToken string) (Bolo, error)
	GetJogoByID(ctx context.Context, id pgtype.UUID) (Jogo, error)
	GetRanking(ctx context.Context, bolaoID pgtype.UUID) ([]GetRankingRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IsParticipante(ctx context.Context, arg IsParticipanteParams) (bool, error)
	JoinBolao(ctx context.Context, arg JoinBolaoParams) (Participante, error)
	ListBoloesByUser(ctx context.Context, userID pgtype.UUID) ([]Bolo, error)
	ListFinishedJobsWithoutScores(ctx context.Context) ([]Jogo, error)
	ListJogos(ctx context.Context) ([]Jogo, error)
	ListPalpitesByBolaoAndJogo(ctx context.Context, arg ListPalpitesByBolaoAndJogoParams) ([]ListPalpitesByBolaoAndJogoRow, error)
	ListPalpitesByBolaoAndUser(ctx context.Context, arg ListPalpitesByBolaoAndUserParams) ([]Palpite, error)
	ListPalpitesByJogo(ctx context.Context, jogoID pgtype.UUID) ([]Palpite, error)
	ListParticipantesByBolao(ctx context.Context, bolaoID pgtype.UUID) ([]ListParticipantesByBolaoRow, error)
	RegenerateInviteToken(ctx context.Context, arg RegenerateInviteTokenParams) (Bolo, error)
	UpdatePalpitePontos(ctx context.Context, arg UpdatePalpitePontosParams) error
	UpsertJogo(ctx context.Context, arg UpsertJogoParams) (Jogo, error)
	UpsertPalpite(ctx context.Context, arg UpsertPalpiteParams) (Palpite, error)
	UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
