// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxa.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelarProposta = `-- name: CancelarProposta :exec
DELETE FROM taxa_entrada_propostas WHERE bolao_id = $1
`

func (q *Queries) CancelarProposta(ctx context.Context, bolaoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelarProposta, bolaoID)
	return err
}

const countParticipantesNaMomento = `-- name: CountParticipantesNaMomento :one
SELECT COUNT(*) FROM participantes
WHERE bolao_id = $1 AND joined_at <= $2
`

type CountParticipantesNaMomentoParams struct {
	BolaoID  pgtype.UUID        `json:"bolao_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CountParticipantesNaMomento(ctx context.Context, arg CountParticipantesNaMomentoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipantesNaMomento, arg.BolaoID, arg.JoinedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotosFavoraveis = `-- name: CountVotosFavoraveis :one
SELECT COUNT(*) FROM taxa_entrada_votos tv
JOIN participantes p ON p.user_id = tv.user_id AND p.bolao_id = $2
WHERE tv.proposta_id = $1 AND tv.aprovado = true AND p.joined_at <= $3
`

type CountVotosFavoraveisParams struct {
	PropostaID pgtype.UUID        `json:"proposta_id"`
	BolaoID    pgtype.UUID        `json:"bolao_id"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
}

// Counts favorable votes only from participants eligible at proposal time (joined_at <= proposta.created_at).
// This ensures the same population is used for both total and favorable counts.
func (q *Queries) CountVotosFavoraveis(ctx context.Context, arg CountVotosFavoraveisParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVotosFavoraveis, arg.PropostaID, arg.BolaoID, arg.JoinedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const definirTaxa = `-- name: DefinirTaxa :one
UPDATE boloes
SET taxa_entrada = $2, updated_at = NOW()
WHERE id = $1 AND taxa_entrada IS NULL
RETURNING id, name, admin_id, invite_token, created_at, updated_at, retroativo_enabled, taxa_entrada, wa_group_jid, wa_notifications_enabled
`

type DefinirTaxaParams struct {
	ID          pgtype.UUID    `json:"id"`
	TaxaEntrada pgtype.Numeric `json:"taxa_entrada"`
}

func (q *Queries) DefinirTaxa(ctx context.Context, arg DefinirTaxaParams) (Bolo, error) {
	row := q.db.QueryRow(ctx, definirTaxa, arg.ID, arg.TaxaEntrada)
	var i Bolo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdminID,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetroativoEnabled,
		&i.TaxaEntrada,
		&i.WaGroupJid,
		&i.WaNotificationsEnabled,
	)
	return i, err
}

const getMeuVoto = `-- name: GetMeuVoto :one
SELECT aprovado FROM taxa_entrada_votos WHERE proposta_id = $1 AND user_id = $2
`

type GetMeuVotoParams struct {
	PropostaID pgtype.UUID `json:"proposta_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMeuVoto(ctx context.Context, arg GetMeuVotoParams) (bool, error) {
	row := q.db.QueryRow(ctx, getMeuVoto, arg.PropostaID, arg.UserID)
	var aprovado bool
	err := row.Scan(&aprovado)
	return aprovado, err
}

const getPropostaAtiva = `-- name: GetPropostaAtiva :one
SELECT id, bolao_id, valor, proposta_por, created_at FROM taxa_entrada_propostas WHERE bolao_id = $1
`

func (q *Queries) GetPropostaAtiva(ctx context.Context, bolaoID pgtype.UUID) (TaxaEntradaProposta, error) {
	row := q.db.QueryRow(ctx, getPropostaAtiva, bolaoID)
	var i TaxaEntradaProposta
	err := row.Scan(
		&i.ID,
		&i.BolaoID,
		&i.Valor,
		&i.PropostaPor,
		&i.CreatedAt,
	)
	return i, err
}

const getPropostaAtivaForUpdate = `-- name: GetPropostaAtivaForUpdate :one
SELECT id, bolao_id, valor, proposta_por, created_at FROM taxa_entrada_propostas WHERE bolao_id = $1 FOR UPDATE
`

func (q *Queries) GetPropostaAtivaForUpdate(ctx context.Context, bolaoID pgtype.UUID) (TaxaEntradaProposta, error) {
	row := q.db.QueryRow(ctx, getPropostaAtivaForUpdate, bolaoID)
	var i TaxaEntradaProposta
	err := row.Scan(
		&i.ID,
		&i.BolaoID,
		&i.Valor,
		&i.PropostaPor,
		&i.CreatedAt,
	)
	return i, err
}

const getTaxaEntrada = `-- name: GetTaxaEntrada :one
SELECT taxa_entrada FROM boloes WHERE id = $1
`

func (q *Queries) GetTaxaEntrada(ctx context.Context, id pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTaxaEntrada, id)
	var taxa_entrada pgtype.Numeric
	err := row.Scan(&taxa_entrada)
	return taxa_entrada, err
}

const isParticipanteElegivel = `-- name: IsParticipanteElegivel :one
SELECT EXISTS (
    SELECT 1 FROM participantes
    WHERE bolao_id = $1 AND user_id = $2 AND joined_at <= $3
)
`

type IsParticipanteElegivelParams struct {
	BolaoID  pgtype.UUID        `json:"bolao_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

// Returns true if the user was a participant at or before proposta.created_at.
func (q *Queries) IsParticipanteElegivel(ctx context.Context, arg IsParticipanteElegivelParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipanteElegivel, arg.BolaoID, arg.UserID, arg.JoinedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const proporTaxa = `-- name: ProporTaxa :one
INSERT INTO taxa_entrada_propostas (bolao_id, valor, proposta_por)
VALUES ($1, $2, $3)
RETURNING id, bolao_id, valor, proposta_por, created_at
`

type ProporTaxaParams struct {
	BolaoID     pgtype.UUID    `json:"bolao_id"`
	Valor       pgtype.Numeric `json:"valor"`
	PropostaPor pgtype.UUID    `json:"proposta_por"`
}

func (q *Queries) ProporTaxa(ctx context.Context, arg ProporTaxaParams) (TaxaEntradaProposta, error) {
	row := q.db.QueryRow(ctx, proporTaxa, arg.BolaoID, arg.Valor, arg.PropostaPor)
	var i TaxaEntradaProposta
	err := row.Scan(
		&i.ID,
		&i.BolaoID,
		&i.Valor,
		&i.PropostaPor,
		&i.CreatedAt,
	)
	return i, err
}

const registrarVoto = `-- name: RegistrarVoto :one
INSERT INTO taxa_entrada_votos (proposta_id, user_id, aprovado)
VALUES ($1, $2, $3)
ON CONFLICT (proposta_id, user_id) DO NOTHING
RETURNING id, proposta_id, user_id, aprovado, voted_at
`

type RegistrarVotoParams struct {
	PropostaID pgtype.UUID `json:"proposta_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Aprovado   bool        `json:"aprovado"`
}

// ON CONFLICT DO NOTHING: when user already voted, RETURNING yields no rows.
// pgx returns pgx.ErrNoRows, which the service maps to ErrJaVotou.
// Do NOT change to DO UPDATE without updating the service layer.
func (q *Queries) RegistrarVoto(ctx context.Context, arg RegistrarVotoParams) (TaxaEntradaVoto, error) {
	row := q.db.QueryRow(ctx, registrarVoto, arg.PropostaID, arg.UserID, arg.Aprovado)
	var i TaxaEntradaVoto
	err := row.Scan(
		&i.ID,
		&i.PropostaID,
		&i.UserID,
		&i.Aprovado,
		&i.VotedAt,
	)
	return i, err
}
